[build]
  base = "client"
  publish = "client/build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://uber-calculator-backend.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"