services:
  - type: web
    name: uber-calculator-backend
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: node dist/index.js
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: static
    name: uber-calculator-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    rootDir: client
    envVars:
      - key: REACT_APP_API_URL
        value: https://uber-calculator-backend.onrender.com/api
      - key: NODE_ENV
        value: production