services:
  - type: web
    name: uber-calculator-backend
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: node dist/index.js
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EXCHANGE_RATE_API_KEY
        sync: false
